name: mapollage
title: Mapollage
base: core18
version: 2.1.0
summary: Mapollage is a photo kml generator for Google Earth
description: |
    Put your photos on the map.

    https://github.com/trixon/mapollage

grade: stable
architectures: [ amd64 ]
confinement: strict
icon: snap/gui/mapollage.png
license: Apache-2.0

apps:
  mapollage:
    command: bin/launcher
    extensions:
        - gnome-3-34
    plugs:
        - home
        - removable-media

parts:
  mapollage:
    plugin: dump
    source: https://github.com/trixon/mapollage/releases/download/v$SNAPCRAFT_PROJECT_VERSION/mapollage-$SNAPCRAFT_PROJECT_VERSION-bin.zip
    #source: /root/project/mapollage-$SNAPCRAFT_PROJECT_VERSION-bin.zip
    source-type: zip
    organize:
      '*' : mapollage

  launcher:
    plugin: dump
    source: snap/local
    organize:
      'launcher': 'bin/'

  apt:
    plugin: nil
    override-build: |
        apt install openjdk-11-jdk -y

  jlink:
    plugin: nil
    after: [apt]
    override-build: |
        rm -rf $SNAPCRAFT_PRIME/jre

        jlink --no-header-files \
            --no-man-pages \
            --strip-debug \
            --compress=1 \
            --add-modules java.base,java.datatransfer,java.desktop,java.logging,java.prefs,java.sql,java.xml,jdk.jfr,jdk.unsupported,jdk.unsupported.desktop \
            --output $SNAPCRAFT_PRIME/jre

        strip -p --strip-unneeded $SNAPCRAFT_PRIME/jre/lib/server/libjvm.so
